### ISSUE TITLE
Should ESLint plugins be dependencies?

### ISSUE THREAD

**Issue by JounQin** [mjolnirjs/mjolnir#10]
The sharable configurations are only used in our own projects, I think marking all the plugins as dependencies rather than installing them by ourselves will be nicer.

And also, we can use the `overrides` feature of ESLint to simplify the usage.

Reference (My own solution):

https://github.com/JounQin/eslint-config-1stg/blob/master/overrides.js

https://github.com/JounQin/eslint-config-1stg/blob/master/.eslintrc.js

**Comment by JounQin** [comment]
Besides, why the repository `mjolnir` is used to share configurations? Is that misleading?

**Comment by leohxj** [comment]
> The sharable configurations are only used in our own projects, I think marking all the plugins as dependencies rather than installing them by ourselves will be nicer.
参考的 airbnb， 是把 plugin 安装都交给使用的项目去安装。（但是好像是 eslint 的问题导致的）
eslint v6 好像修复了寻找插件位置的问题吧。
依赖我们确实可以全部做完自己 config 的 `dependencies`.


> And also, we can use the overrides feature of ESLint to simplify the usage.
这点我个人觉得太隐晦，所以是用多个配置组合的方式完成。

> Besides, why the repository mjolnir is used to share configurations? Is that misleading?
我是想把 mjolnir 做为一个脚手架工具，里面包含了 cli, configs.

**Comment by leohxj** [comment]
对应的修改我合到了 master 分支，可以再 review 下。

**Comment by JounQin** [comment]
Well done.
